Adding examples for wavelength and detector.
sunpy/sunpy-soar pull request #127
Opened 2024-06-18 06:06 UTC by NucleonGodX

This PR is a part of GSoC 2024, as the attributes detector and wavelength have been implemented, some gallery examples have been added for helping user understand their functioning.(#121)

2024-06-18 06:14 UTC, nabobalis commented
What's the difference between the two examples?

2024-06-18 06:57 UTC, NucleonGodX commented
> What's the difference between the two examples?

So I've kept two examples from the view of instruments differentiation, two of instruments give range of wavelength and not the single wavelength column, thats why In my opinion it would be better if we show both the workings to the user.

And I think we would be interested in showing what happens in both conditions when a range is provided and when a single wavelength is provided for all instruments, so covering all these cases in one example felt quite long to me.

2024-06-18 19:51 UTC, nabobalis commented
> > What's the difference between the two examples?
> 
> So I've kept two examples from the view of instruments differentiation, two of instruments give range of wavelength(wavemin wavemax) and not the single wavelength column, thats why In my opinion it would be better if we show both the workings to the user.
> 
> And I think we would be interested in showing what happens in both conditions when a range is provided and when a single wavelength is provided for all instruments, so covering all these cases in one example felt quite long to me.

This feels more like one large example or even like a tutorial than two separate examples.
I don't see the need to separate this. 

Could you try to work it into one large example instead?

2024-06-19 15:12 UTC, hayesla commented
Following discussion on the GSOC update call, we decided that this should be more like a "how to guide" with a simple example for the example gallery. 

The hot to guide could be a bit more detailed description of how sunpy-soar works and how you can build different searches etc

2024-06-21 19:42 UTC, nabobalis commented on changelog/121.feature.rst
> +Created a how-to guide, added a guide to query wavelength and added a gallery example for `wavelength` and `detector`.
I think this should be a .doc. and not a .feature.

2024-06-21 19:43 UTC, nabobalis commented on changelog/121.feature.rst
> +Created a how-to guide, added a guide to query wavelength and added a gallery example for `wavelength` and `detector`.
```suggestion
Created a how-to guide with a guide on how to query wavelength.
Added a short gallery example on how to query using ``wavelength`` and ``detector``.
```

2024-06-21 19:43 UTC, nabobalis commented on examples/detector_wavelength.py
> +import sunpy_soar  # NOQA: F401
```suggestion
# Importing sunpy_soar registers the client with sunpy

import sunpy_soar  # NOQA: F401
```

2024-06-21 19:44 UTC, nabobalis commented on examples/detector_wavelength.py
> +#####################################################
I think these are too short, they should be 80 characters long.

2024-06-21 19:44 UTC, nabobalis commented on examples/detector_wavelength.py
> +# print(files)
```suggestion
```

2024-06-21 19:44 UTC, nabobalis commented on examples/detector_wavelength.py
> +#####################################################
```suggestion
wavelength = a.Wavelength(121.6 * u.AA)

#####################################################
```

2024-06-21 19:44 UTC, nabobalis commented on examples/detector_wavelength.py
> +result
```suggestion
print(result)
```

2024-06-21 19:45 UTC, nabobalis commented on docs/how_to/wavelength.rst
> +for instruments SPICE and STIX we do not get any meaningful data for wavelength.
```suggestion
For instruments EUI, METIS and SOLOHI we get query results in form of wavelength, for instrument PHI we get query results in form of wavemin and wavemax and for instruments SPICE and STIX we do not get any meaningful data for wavelength.
```
We go for one sentence per line.

2024-06-21 19:52 UTC, nabobalis commented on docs/how_to/wavelength.rst
> +
```suggestion

```

2024-07-03 23:12 UTC, nabobalis commented on examples/detector_wavelength.py
> +import sunpy_soar  # NOQA: F401
```suggestion
# Importing sunpy_soar registers the client with sunpy Fido

import sunpy_soar  # NOQA: F401
```

2024-07-03 23:12 UTC, nabobalis approved these changes

2024-07-03 23:15 UTC, nabobalis commented
pre-commit autofix

2024-07-03 23:41 UTC, nabobalis commented
This needs the main PR merged in.

2024-07-07 17:13 UTC, nabobalis commented on changelog/121.doc.rst
> +Added a short gallery example on how to query using ``wavelength`` and ``detector``.
We should link to both using sphinx interlinks.

2024-07-07 17:13 UTC, nabobalis commented on docs/how_to/wavelength.rst
> +
```suggestion

```

2024-07-07 17:13 UTC, nabobalis commented on docs/how_to/wavelength.rst
> +
```suggestion

```

2024-07-08 04:33 UTC, nabobalis commented on docs/how_to/wavelength.rst
> +    >>> import astropy.units as u
```suggestion
.. code-block:: python

    >>> import astropy.units as u
```

Not sure if this will fix the error

2024-07-08 04:33 UTC, nabobalis commented on docs/how_to/wavelength.rst
> +    >>> wavelength = a.Wavelength(580 * u.AA, 640 * u.AA)
```suggestion
.. code-block:: python

    >>> wavelength = a.Wavelength(580 * u.AA, 640 * u.AA)
```

2024-07-08 05:19 UTC, NucleonGodX commented on docs/how_to/wavelength.rst
> +    >>> import astropy.units as u
I think it will.

2024-07-18 07:01 UTC, hayesla requested changes

2024-07-18 07:01 UTC, hayesla commented on docs/how_to/wavelength.rst
> +For instruments EUI, METIS and SOLOHI we get query results in form of wavelength, for instrument PHI we get query results in form of wavemin and wavemax and for instruments SPICE and STIX we do not g
```suggestion
For instruments EUI, METIS and SOLOHI we get query results in form of wavelength. However, at this time we cannot search for wavelengths for instruments SPICE, PHI, and STIX as this information is not yet available in the SOAR.
```

2024-07-18 15:29 UTC, nabobalis commented on examples/detector_wavelength.py
> +import sunpy_soar  # NOQA: F401
Unfortunately yes, the precommit will remove it as its not used directly in the code.

2024-07-18 19:00 UTC, nabobalis commented on docs/how_to/wavelength.rst
> +``sunpy-soar`` provides a convenient methods to construct queries using `a.Wavelength` for several different remote sensing instruments available through the SOAR.
```suggestion
``sunpy-soar`` provides a convenient methods to construct queries using ``a.Wavelength`` for several different remote sensing instruments available through the SOAR.
```

2024-07-18 19:00 UTC, nabobalis commented on docs/how_to/wavelength.rst
> +In this guide, we will demonstrate how we can query data using `a.Wavelength` for different instruments.
```suggestion
In this guide, we will demonstrate how we can query data using ``a.Wavelength`` for different instruments.
```

2024-07-18 19:00 UTC, nabobalis commented on docs/how_to/wavelength.rst
> +For instruments EUI, METIS and SOLOHI we get query results in form of wavelength. However, at this time we cannot search for wavelengths for instruments SPICE, PHI, and STIX as this information is no
```suggestion
For instruments EUI, METIS and SOLOHI we get query results in form of wavelength. 
However, at this time we cannot search for wavelengths for instruments SPICE, PHI, and STIX as this information is not yet available in the SOAR.
```

2024-07-18 19:01 UTC, nabobalis commented on docs/index.rst
> +   how_to/index
this should be higher, maybe just below the gallery.

2024-07-18 22:47 UTC, nabobalis commented on docs/how_to/wavelength.rst
> +********************************************************************************************
```suggestion
***************************************************************
Query for Solar Orbiter data using the ``Wavelength`` attribute
***************************************************************
```

2024-07-19 16:36 UTC, nabobalis approved these changes

2024-07-31 13:12 UTC, hayesla approved these changes

2024-07-31 13:12 UTC, hayesla commented on changelog/121.doc.rst
> +Created a how-to guide with a guide on how to query wavelength.(:ref:`sunpy-soar-how-to-query-wavelength`)
```suggestion
Created a how-to guide with a guide on how to build a query using the wavelength attribute.(:ref:`sunpy-soar-how-to-query-wavelength`)
```

2024-07-31 13:12 UTC, hayesla commented on changelog/121.doc.rst
> +Added a short gallery example on how to query using ``wavelength`` and ``detector``.(:ref:`sphx_glr_generated_gallery_detector_wavelength.py`)
```suggestion
Added a short gallery example on how to query using ``wavelength`` and ``detector`` attributes.(:ref:`sphx_glr_generated_gallery_detector_wavelength.py`)
```

2024-07-31 13:12 UTC, hayesla commented on docs/how_to/wavelength.rst
> +``sunpy-soar`` provides a convenient methods to construct queries using ``a.Wavelength`` for several different remote sensing instruments available through the SOAR.
```suggestion
``sunpy-soar`` provides convenient methods to construct queries using ``a.Wavelength`` for several different remote sensing instruments available through the SOAR.
```

2024-07-31 15:25 UTC, merged