Adding support for query by Solar Distance
sunpy/sunpy-soar pull request #137
Opened 2024-07-19 16:33 UTC by NucleonGodX

As the #134  suggested adding support for querying by solar distance. This pull request extends support for another `REQUEST` method, `doQueryFilteredByDistance`.

2024-07-19 16:39 UTC, nabobalis commented
Looks like there is a file conflict with main

2024-07-19 16:44 UTC, NucleonGodX commented
> Looks like there is a file conflict with main

yep, I'll fix it.

2024-07-19 16:46 UTC, nabobalis commented on sunpy_soar/tests/test_sunpy_soar.py
```suggestion


```

2024-07-19 16:46 UTC, nabobalis commented on sunpy_soar/tests/test_sunpy_soar.py
> +    assert res.file_num == 172
Can we check the distance values?

2024-07-19 17:01 UTC, NucleonGodX commented on sunpy_soar/tests/test_sunpy_soar.py
> +    assert res.file_num == 172
Actually we aren't adding anything in the table related to the distance, its just that entire query is being filtered by these values with the new parameter "&Distance(dmin, dmax)" which gets appended in the query.

2024-07-19 17:07 UTC, nabobalis commented on sunpy_soar/tests/test_sunpy_soar.py
> +    assert res.file_num == 172
So can we check it works?

2024-07-19 17:16 UTC, NucleonGodX commented on sunpy_soar/tests/test_sunpy_soar.py
> +    assert res.file_num == 172
Alright, I'll look into that.

2024-07-19 17:26 UTC, nabobalis commented on sunpy_soar/tests/test_sunpy_soar.py
> +    assert res.file_num == 172
I guess maybe check numbers before and after you add distance?

2024-07-19 17:37 UTC, NucleonGodX commented on sunpy_soar/tests/test_sunpy_soar.py
> +    assert res.file_num == 172
okay, we can do that.

2024-07-19 17:47 UTC, nabobalis commented on sunpy_soar/tests/test_sunpy_soar.py
> +    assert res.file_num == 172
Not sure if thats best as I would like to somehow check if the query is working but maybe as a start.

2024-07-19 17:59 UTC, NucleonGodX commented on sunpy_soar/tests/test_sunpy_soar.py
> +    assert res.file_num == 172
for that maybe we can have a query test for distance that gives us query as output.

2024-07-19 18:01 UTC, nabobalis commented on sunpy_soar/tests/test_sunpy_soar.py
> +    assert res.file_num == 172
Lets try that as well

2024-07-31 13:38 UTC, hayesla commented
thanks for this PR @NucleonGodX !

Some comments to begin with - 
* I think it would be best to pass astropy units to a.soar.Distance rather than just floats.  i.e. `a.soar.Distance(0.2*u.AU, 0.3*u.AU)`, and equivalent distance etc (u.km, u.Mm).
* there seems to be an issue if the passed distances are outside the range e.g. :

```python
>>> res = Fido.search(a.Time("2022-03-30 17:00", "2022-03-30 19:00"), 
                  a.Instrument.eui, a.Provider.soar, a.soar.Distance(0.2, 0.9))
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
Cell In[11], line 1
----> 1 res = Fido.search(a.Time("2022-03-30 17:00", "2022-03-30 19:00"), 
      2                   a.Instrument.eui, a.Provider.soar, a.soar.Distance(0.2, 0.9))

File ~/opt/miniconda3/envs/sunpysoar_dev/lib/python3.11/site-packages/sunpy/net/fido_factory.py:314, in UnifiedDownloaderFactory.search(self, *query)
    268 """
    269 Query for data in form of multiple parameters.
    270 
   (...)
    311 parts individually.
    312 """
    313 query = attr.and_(*query)
--> 314 results = query_walker.create(query, self)
    316 # If we have searched the VSO but no results were returned, but another
    317 # client generated results, we drop the empty VSO results for tidiness.
    318 # This is because the VSO _can_handle_query is very broad because we
    319 # don't know the full list of supported values we can search for (yet).
    320 results = [r for r in results if not isinstance(r, vso.VSOQueryResponseTable) or len(r) > 0]

File ~/opt/miniconda3/envs/sunpysoar_dev/lib/python3.11/site-packages/sunpy/net/attr.py:613, in AttrWalker.create(self, *args, **kwargs)
    609 def create(self, *args, **kwargs):
    610     """
    611     Call the create function(s) matching the arguments to this method.
    612     """
--> 613     return self.createmm(self, *args, **kwargs)

File ~/opt/miniconda3/envs/sunpysoar_dev/lib/python3.11/site-packages/sunpy/util/functools.py:18, in seconddispatch.<locals>.wrapper(*args, **kwargs)
     17 def wrapper(*args, **kwargs):
---> 18     return dispatcher.dispatch(args[1].__class__)(*args, **kwargs)

File ~/opt/miniconda3/envs/sunpysoar_dev/lib/python3.11/site-packages/sunpy/net/fido_factory.py:243, in _create_and(walker, query, factory)
    241 @query_walker.add_creator(attr.AttrAnd)
    242 def _create_and(walker, query, factory):
--> 243     return factory._make_query_to_client(*query.attrs)

File ~/opt/miniconda3/envs/sunpysoar_dev/lib/python3.11/site-packages/sunpy/net/fido_factory.py:485, in UnifiedDownloaderFactory._make_query_to_client(self, *query)
    483     if isinstance(tmpclient, vso.VSOClient):
    484         kwargs = dict(response_format="table")
--> 485     results.append(tmpclient.search(*query, **kwargs))
    487 # This method is called by `search` and the results are fed into a
    488 # UnifiedResponse object.
    489 return results

File ~/dev_things/sunpy-soar/sunpy_soar/client.py:33, in SOARClient.search(self, *query, **kwargs)
     31     if "provider='SOAR'" in query_parameters:
     32         query_parameters.remove("provider='SOAR'")
---> 33     results.append(self._do_search(query_parameters))
     34 table = astropy.table.vstack(results)
     35 qrt = QueryResponseTable(table, client=self)

File ~/dev_things/sunpy-soar/sunpy_soar/client.py:189, in SOARClient._do_search(query)
    187 r = requests.get(f"{tap_endpoint}/sync", params=payload)
    188 log.debug(f"Sent query: {r.url}")
--> 189 r.raise_for_status()
    191 try:
    192     response_json = r.json()

File ~/opt/miniconda3/envs/sunpysoar_dev/lib/python3.11/site-packages/requests/models.py:1021, in Response.raise_for_status(self)
   1016     http_error_msg = (
   1017         f"{self.status_code} Server Error: {reason} for url: {self.url}"
   1018     )
   1020 if http_error_msg:
-> 1021     raise HTTPError(http_error_msg, response=self)

HTTPError: 400 Client Error:  for url: [http://soar.esac.esa.int/soar-sl-tap/tap/sync?REQUEST=doQueryFilteredByDistance&LANG=ADQL&FORMAT=json&QUERY=SELECT+h1.instrument,%20h1.descriptor,%20h1.level,%20h1.begin_time,%20h1.end_time,%20h1.data_item_id,%20h1.filesize,%20h1.filename,%20h1.soop_name,%20h2.detector,%20h2.wavelength,%20h2.dimension_index+FROM+v_sc_data_item%20AS%20h1%20JOIN%20v_eui_sc_fits%20AS%20h2%20USING%20(data_item_oid)+WHERE+h1.begin_time%3E='2022-03-30+17:00:00'+AND+h1.begin_time%3C='2022-03-30+19:00:00'+AND+h2.dimension_index='1'+AND+h1.instrument='EUI'&DISTANCE(0.2,0.9](http://soar.esac.esa.int/soar-sl-tap/tap/sync?REQUEST=doQueryFilteredByDistance&LANG=ADQL&FORMAT=json&QUERY=SELECT+h1.instrument,%20h1.descriptor,%20h1.level,%20h1.begin_time,%20h1.end_time,%20h1.data_item_id,%20h1.filesize,%20h1.filename,%20h1.soop_name,%20h2.detector,%20h2.wavelength,%20h2.dimension_index+FROM+v_sc_data_item%20AS%20h1%20JOIN%20v_eui_sc_fits%20AS%20h2%20USING%20(data_item_oid)+WHERE+h1.begin_time%3E=%272022-03-30+17:00:00%27+AND+h1.begin_time%3C=%272022-03-30+19:00:00%27+AND+h2.dimension_index=%271%27+AND+h1.instrument=%27EUI%27&DISTANCE(0.2,0.9))
```

2024-07-31 13:43 UTC, hayesla commented
so it seems like if you pass anything outside of (0.28, 1), it doesnt like that - so we'd need to raise a warning etc. 

Some tests testing this are also needed.

2024-08-03 15:04 UTC, NucleonGodX commented
I'll push all the needful changes.

2024-08-06 13:44 UTC, hayesla requested changes
This looks good @NucleonGodX !

I think it also needs some tests for which the wrong units are passed to test for the warning raised. Similarly a test for when you build a search outside of (0.28, 1)

2024-08-06 13:44 UTC, hayesla commented on sunpy_soar/attrs.py
> +            dist_max = dist_min
does this actually work though - like if you have a range with the same values in both it wont work in the query, right? So we should force people to give a range.

2024-08-06 13:44 UTC, hayesla commented on sunpy_soar/attrs.py
> +
`@quantity_input(dist_min=u.m, dist_max=u.m)`

2024-08-06 13:44 UTC, hayesla commented on sunpy_soar/attrs.py
> +    def __init__(self, dist_min, dist_max=None):
```suggestion
    def __init__(self, dist_min: u.Quantity, dist_max: u.Quantity = None):
```

2024-08-06 13:44 UTC, hayesla commented on sunpy_soar/attrs.py
> +            raise TypeError(msg)
```suggestion

```

2024-08-06 13:44 UTC, hayesla commented on sunpy_soar/attrs.py
> +            raise u.UnitsError(msg)
```suggestion

```
this should also be taken in account with the u.quantity_input

2024-08-06 13:44 UTC, hayesla commented on examples/solar_distance_query.py
> +instrument = a.Instrument("METIS")
can you make this EUI instead. And maybe EUI with the product being `eui_hrieuv174_image` rather than using METIS. Users would be more interested in building this search for with the EUI instrument, and specifically the HRI telescope.

2024-08-06 13:44 UTC, hayesla commented on examples/solar_distance_query.py
> +# To then download the data, you would use Fido.fetch(result), which will download the data locally.
can you also show an example further down where you can build a search without passing the time attribute?

2024-08-07 05:49 UTC, NucleonGodX commented on sunpy_soar/attrs.py
> +            dist_max = dist_min
> does this actually work though - like if you have a range with the same values in both it wont work in the query, right? So we should force people to give a range.

Yeah, makes sense.

2024-08-07 05:50 UTC, NucleonGodX commented on examples/solar_distance_query.py
> +# To then download the data, you would use Fido.fetch(result), which will download the data locally.
You mean, with passing time attribute?

2024-08-07 07:22 UTC, NucleonGodX commented
I'll fix the failing test and change the instrument to EUI once I reach home.

2024-08-07 10:31 UTC, hayesla commented on examples/solar_distance_query.py
> +# To then download the data, you would use Fido.fetch(result), which will download the data locally.
ah sorry ignore me!

2024-08-07 15:19 UTC, hayesla requested changes
This is looking great @NucleonGodX!

I dont know what the test fails are exactly, but once they pass good to go

2024-08-07 15:19 UTC, hayesla commented on sunpy_soar/attrs.py
> +    def __init__(self, dist_min: u.Quantity, dist_max: u.Quantity = None):
```suggestion
    def __init__(self, dist_min: u.Quantity, dist_max: u.Quantity):
```

2024-08-07 15:19 UTC, hayesla commented on sunpy_soar/attrs.py
> +            raise ValueError(msg)
```suggestion
```
I think if you remove the None from the __init__ then you dont need this

2024-08-07 15:19 UTC, hayesla commented on sunpy_soar/tests/test_sunpy_soar.py
> +def test_distance_out_of_bounds_warning(recwarn):
what is the `recwarn` here for?

2024-08-07 18:27 UTC, NucleonGodX commented on sunpy_soar/tests/test_sunpy_soar.py
> +def test_distance_out_of_bounds_warning(recwarn):
Oh, its a pytest fixture provided by the pytest library that allows you to capture warnings emitted during the execution of a test.

2024-08-08 16:18 UTC, NucleonGodX commented
@nabobalis I'll push some changes to fix pre-commit, let me know if they are okay.

2024-08-08 18:34 UTC, nabobalis commented on sunpy_soar/client.py
> +    def _construct_payload(query):  # NOQA: C901
What is C901?

2024-08-08 18:34 UTC, nabobalis commented on sunpy_soar/attrs.py
> +    def __init__(self, dist_min: u.Quantity, dist_max: u.Quantity):  # NOQA: ANN204
This is the missing return annotation?

2024-08-08 19:06 UTC, NucleonGodX commented on sunpy_soar/attrs.py
> +    def __init__(self, dist_min: u.Quantity, dist_max: u.Quantity):  # NOQA: ANN204
Yes.

2024-08-08 19:07 UTC, NucleonGodX commented on sunpy_soar/client.py
> +    def _construct_payload(query):  # NOQA: C901
Its about the function being too complex.

2024-08-08 20:38 UTC, nabobalis commented on sunpy_soar/client.py
> +    def _construct_payload(query):  # NOQA: C901
Oh that should be added to the global ignore.

2024-08-08 20:39 UTC, nabobalis commented on sunpy_soar/attrs.py
> +    def __init__(self, dist_min: u.Quantity, dist_max: u.Quantity):  # NOQA: ANN204
Does this not return type self?

2024-08-09 16:40 UTC, NucleonGodX commented on sunpy_soar/attrs.py
> +    def __init__(self, dist_min: u.Quantity, dist_max: u.Quantity):  # NOQA: ANN204
nope

2024-08-09 16:40 UTC, NucleonGodX commented on sunpy_soar/client.py
> +    def _construct_payload(query):  # NOQA: C901
alright!

2024-08-09 16:53 UTC, nabobalis commented on sunpy_soar/attrs.py
> +    def __init__(self, dist_min: u.Quantity, dist_max: u.Quantity):  # NOQA: ANN204
Fair enough.

2024-08-18 19:26 UTC, hayesla approved these changes

2024-08-18 19:27 UTC, merged