Add VSO info to REDAME
sunpy/sunpy-soar pull request #45
Opened 2022-08-16 16:19 UTC by dstansby

Fixes https://github.com/sunpy/sunpy-soar/issues/25.

2022-08-28 11:10 UTC, ebuchlin commented on README.rst
> +redundant as the ``sunpy`` core package will be able to search the VSO for all Solar Orbiter data.
Just a question: how "redundant" is "redundant"? I mean: having several data providers for the same data is not completely useless (outages, load balancing, choosing the server with the best performance/connectivity...).

2022-09-07 08:19 UTC, dstansby commented on README.rst
> +redundant as the ``sunpy`` core package will be able to search the VSO for all Solar Orbiter data.
I had more of a think, and agree it will probably never be redundant, partly because the VSO are only adding data on a best efforts basis, but SOAR is the official repository.

2022-09-07 08:24 UTC, nabobalis submitted a review, later dismissed

2022-09-07 08:35 UTC, Cadair requested changes

2022-09-07 08:35 UTC, Cadair commented on README.rst
> +order to make sure all available data are queried.
I think this is a little reductionist. To my mind the reasons you might want to use SOAR is if you are solely interested in solar orbiter data and you know or are willing to learn how to query the SOAR. On the other hand, using VSO lets you easily query multiple instruments from different data providers *with a single data model* and you don't need to know how to search the SOAR to get the available solar orbiter data from the VSO (if you already have VSO / experience).

To make this point, I could easily without reference to the docs find EUI data in VSO, but I would have to lookup what dataset or series or whatever it is in SOAR to do the same thing. Brushing over this feels misleading at best.

2022-09-07 09:05 UTC, dstansby commented on README.rst
> +order to make sure all available data are queried.
How about now?

2022-09-07 09:29 UTC, Cadair approved these changes

2022-09-07 09:29 UTC, merged

2022-09-07 09:30 UTC, Cadair commented on README.rst
> +order to make sure all available data are queried.
:+1: Still reads a little negative, but it's much better.